require 'rails_helper'

feature 'Colors' do
  scenario 'Stanford Primary Colors' do
    visit '/styleguide/colors'
    expect(page).to have_css 'h3', text: /Stanford Primary Colors/
    expect(page).to have_css '.color-variable-name', text: '$color-cardinal-red'
    expect(page).to have_css '.color-variable-name', text: '$color-cool-gray'
    expect(page).to have_css '.color-variable-name', text: '$color-black'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-467'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-465'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-403'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-401'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-7527'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-5665'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-445'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-405'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-1817'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-7526'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-3165'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-561'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-262'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-2925'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-3145'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-334'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-7511'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-144'
    expect(page).to have_css '.color-variable-name', text: '$color-pantone-124'
  end
  scenario 'Stanford Web Colors' do
    visit '/styleguide/colors'
    expect(page).to have_css 'h3', text: /Stanford Primary Colors/
    expect(page).to have_css '.color-variable-name', text: '$color-cardinal-red'
    expect(page).to have_css '.color-variable-name', text: '$color-dark-red'
    expect(page).to have_css '.color-variable-name', text: '$color-blackish'
    expect(page).to have_css '.color-variable-name', text: '$color-black-80'
    expect(page).to have_css '.color-variable-name', text: '$color-gray'
    expect(page).to have_css '.color-variable-name', text: '$color-gray-90'
    expect(page).to have_css '.color-variable-name', text: '$color-gray-60'
    expect(page).to have_css '.color-variable-name', text: '$color-sandstone'
    expect(page).to have_css '.color-variable-name', text: '$color-sandstone-50'
    expect(page).to have_css '.color-variable-name', text: '$color-sandstone-35'
    expect(page).to have_css '.color-variable-name', text: '$color-sandstone-25'
    expect(page).to have_css '.color-variable-name', text: '$color-sandstone-20'
    expect(page).to have_css '.color-variable-name', text: '$color-beige'
    expect(page).to have_css '.color-variable-name', text: '$color-beige-85'
    expect(page).to have_css '.color-variable-name', text: '$color-beige-60'
    expect(page).to have_css '.color-variable-name', text: '$color-beige-40'
    expect(page).to have_css '.color-variable-name', text: '$color-beige-30'
    expect(page).to have_css '.color-variable-name', text: '$color-beige-20'
    expect(page).to have_css '.color-variable-name', text: '$color-beige-10'
    expect(page).to have_css '.color-variable-name', text: '$color-beige-05'
  end
end