require 'rails_helper'

feature 'Icons' do
  scenario 'Icon defaults' do
    visit '/styleguide/icons'
    expect(page).to have_css 'h3', text: 'Icons'
    expect(page).to have_css '.sul-i-arrow-down-8-char', text: 'f13e'
    expect(page).to have_css '.sul-i-arrow-left-3-char', text: 'f108'
    expect(page).to have_css '.sul-i-arrow-left-8-char', text: 'f109'
    expect(page).to have_css '.sul-i-arrow-right-3-char', text: 'f10a'
    expect(page).to have_css '.sul-i-arrow-right-8-char', text: 'f10b'
    expect(page).to have_css '.sul-i-arrow-up-8-char', text: 'f13f'
    expect(page).to have_css '.sul-i-book-open-4-char', text: 'f10c'
    expect(page).to have_css '.sul-i-bookmark-all-1-char', text: 'f10d'
    expect(page).to have_css '.sul-i-books-library-char', text: 'f10e'
    expect(page).to have_css '.sul-i-box-1-char', text: 'f10f'
    expect(page).to have_css '.sul-i-bubble-chat-2-char', text: 'f110'
    expect(page).to have_css '.sul-i-camera-film-1-char', text: 'f111'
    expect(page).to have_css '.sul-i-check-box-1-char', text: 'f112'
    expect(page).to have_css '.sul-i-cube-char', text: 'f113'
    expect(page).to have_css '.sul-i-download-3-char', text: 'f106'
    expect(page).to have_css '.sul-i-email-char', text: 'f114'
    expect(page).to have_css '.sul-i-expand-1-char', text: 'f115'
    expect(page).to have_css '.sul-i-file-acrobat-char', text: 'f13a'
    expect(page).to have_css '.sul-i-file-code-1-char', text: 'f137'
    expect(page).to have_css '.sul-i-file-excel-char', text: 'f13b'
    expect(page).to have_css '.sul-i-file-new-1-char', text: 'f140'
    expect(page).to have_css '.sul-i-file-music-1-char', text: 'f116'
    expect(page).to have_css '.sul-i-file-picture-char', text: 'f136'
    expect(page).to have_css '.sul-i-file-powerpoint-char', text: 'f13d'
    expect(page).to have_css '.sul-i-file-text-document-char', text: 'f139'
    expect(page).to have_css '.sul-i-file-video-3-char', text: 'f138'
    expect(page).to have_css '.sul-i-file-words-char', text: 'f13c'
    expect(page).to have_css '.sul-i-file-zipped-char', text: 'f134'
    expect(page).to have_css '.sul-i-graph-bar-2-char', text: 'f117'
    expect(page).to have_css '.sul-i-infomation-circle-char', text: 'f104'
    expect(page).to have_css '.sul-i-key-2-char', text: 'f118'
    expect(page).to have_css '.sul-i-layout-4-char', text: 'f119'
    expect(page).to have_css '.sul-i-layout-none-char', text: 'f11a'
    expect(page).to have_css '.sul-i-link-3-char', text: 'f107'
    expect(page).to have_css '.sul-i-list-bullets-1-char', text: 'f11b'
    expect(page).to have_css '.sul-i-mouse-char', text: 'f11f'
    expect(page).to have_css '.sul-i-navigation-drawer-1-char', text: 'f120'
    expect(page).to have_css '.sul-i-navigation-drawer-2-char', text: 'f121'
    expect(page).to have_css '.sul-i-navigation-left-2-char', text: 'f122'
    expect(page).to have_css '.sul-i-network-web-char', text: 'f123'
    expect(page).to have_css '.sul-i-news-article-char', text: 'f124'
    expect(page).to have_css '.sul-i-newspaper-char', text: 'f125'
    expect(page).to have_css '.sul-i-notebook-char', text: 'f126'
    expect(page).to have_css '.sul-i-person-1-char', text: 'f127'
    expect(page).to have_css '.sul-i-person-information-1-char', text: 'f128'
    expect(page).to have_css '.sul-i-picture-2-char', text: 'f129'
    expect(page).to have_css '.sul-i-plug-1-char', text: 'f12a'
    expect(page).to have_css '.sul-i-print-text-char', text: 'f12b'
    expect(page).to have_css '.sul-i-quote-1-char', text: 'f12c'
    expect(page).to have_css '.sul-i-search-char', text: 'f12d'
    expect(page).to have_css '.sul-i-share-char', text: 'f105'
    expect(page).to have_css '.sul-i-transfer-3-char', text: 'f12e'
    expect(page).to have_css '.sul-i-turntable-char', text: 'f12f'
    expect(page).to have_css '.sul-i-view-headline-char', text: 'f130'
    expect(page).to have_css '.sul-i-view-list-char', text: 'f131'
    expect(page).to have_css '.sul-i-view-module-1-char', text: 'f102'
    expect(page).to have_css '.sul-i-window-search-char', text: 'f132'
    expect(page).to have_css '.sul-i-zoom-in-char', text: 'f133'
    # We can only include 100 Streamline icons per our license agreement
    expect(page).to have_css '.icon-example-character-code', maximum: 100
  end
  scenario 'Icon aliases' do
    visit '/styleguide/icons'
    expect(page).to have_css 'h3', text: 'Icon aliases'
    expect(page).to have_css '.icon-example-name', text: 'sul-i-download'
    expect(page).to have_css '.icon-example-name', text: 'sul-i-expand'
    expect(page).to have_css '.icon-example-name', text: 'sul-i-fullscreen'
    expect(page).to have_css '.icon-example-name', text: 'sul-i-singlepage'
    expect(page).to have_css '.icon-example-name', text: 'sul-i-twopage'
    expect(page).to have_css '.icon-example-name', text: 'sul-i-info'
    expect(page).to have_css '.icon-example-name', text: 'sul-i-link'
    expect(page).to have_css '.icon-example-name', text: 'sul-i-gallery'
  end
end
